version: "3.8"
services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    restart: unless-stopped
    networks:
      - share_net
    ports:
      - "5212:5212"
    volumes:
      - temp_data:/data
      - /usr/local/cloudreve/cloudreve/uploads:/cloudreve/uploads
      - /usr/local/cloudreve/cloudreve/conf.ini:/cloudreve/conf.ini
      - /usr/local/cloudreve/cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - /usr/local/cloudreve/cloudreve/avatar:/cloudreve/avatar
    depends_on:
      - aria2
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: unless-stopped
    networks:
      - share_net
    environment:
      - RPC_SECRET=your_aria_rpc_token
      - RPC_PORT=6800
    volumes:
      - /usr/local/cloudreve/aria2/config:/config
      - temp_data:/data
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: cloudreve aria2 watchtower --cleanup --schedule "0 30 6 * * *"
    networks:
      - share_net
volumes:
  temp_data:
    driver: local
    driver_opts:
      type: none
      device: /usr/local/cloudreve/data
      o: bind
networks:
  share_net:
    driver: bridge
